# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-29 20:29
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Educacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pregunta',
            name='nombre',
            field=models.CharField(max_length=200, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_username', message='La pregunta debe de ser solo letras sin caracteres ', regex='^[a-zA-Z0-9\xe1\xe9\xed\xf3\xfa\xf1\xd1\xbf? ]*$')]),
        ),
    ]
