# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-29 20:33
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Educacion', '0002_auto_20170629_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='respuesta',
            name='titulo',
            field=models.CharField(max_length=60, validators=[django.core.validators.RegexValidator(code='invalid_username', message='La encuesta no debe poseer caracteres ni numeros ', regex='^[a-zA-Z0-9\xe1\xe9\xed\xf3\xfa$ ]*$')]),
        ),
    ]
