# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-03 18:06
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Educacion', '0005_auto_20170629_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encuesta',
            name='titulo',
            field=models.CharField(max_length=50, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_username', message='La encuesta no debe poseer caracteres ni numeros ', regex='^[a-zA-Z0-9\xe1\xe9\xed\xf3\xfa\xf1\xd1 ]*$')]),
        ),
    ]
